<?php
/*
Sort a String with the Given Template
The function is given two strings $t - template, $s - to be sorted. Sort the characters in $s such that if the character is present in $t then it is sorted according to the order in $t and other characters are sorted alphabetically after the ones found in $t.

Examples
customSortt("edc", "abcdefzyx") ➞ "edcabfxyz"

customSortt("fby", "abcdefzyx") ➞ "fbyacdexz"

customSortt("", "abcdefzyx") ➞ "abcdefxyz"

customSortt("", "") ➞ ""
Notes
The characters in $t and $s are all lower-case.
*/
function customSort($t, $s) {
  $templateArray = str_split($t);
  $strForSortArr = str_split($s);
  $templateSortable = [];
  $normalSortable = [];
  foreach ($strForSortArr as $char) {
    if (in_array($char, $templateArray))
      array_push($templateSortable, $char);
    else 
      array_push($normalSortable, $char);
  }
  usort(
    $templateSortable,
    function($a, $b) use($templateArray) {
      if ($a == $b) return 0;
      return (
        array_search(
          $a,
          $templateArray
        ) < array_search(
          $b,
          $templateArray
        )
      )?-1:1;
    }
  );
  sort($normalSortable);
  return join("", $templateSortable)
       . join("", $normalSortable);
}

echo customSort("edc", "abcdefzyx") === "edcabfxyz";
echo customSort("fby", "abcdefzyx") === "fbyacdexz";
echo customSort("", "abcdefzyx") === "abcdefxyz";
echo customSort("", "") === "";
echo customSort('cteqh', 'xnjanztmhg') === "thagjmnnxz";
echo customSort('jv', 'cxkafinfiuhnnaracsztbrcwaifwattzavwohoqskauififucq') === "vaaaaaaabccccfffffhhiiiiikknnnooqqrrsstttuuuwwwxzz";
echo customSort('xtz', 'uhgpqydzwtsemucfidpvrvormgfjefpqeprvmyiazqokmnhdwvyglngcsriw') === "tzzaccdddeeefffgggghhiiijklmmmmnnooppppqqqrrrrssuuvvvvwwwyyy";
echo customSort('eyuti', 'iuanyojxqbmihzyvjunb') === "yyuuiiabbhjjmnnoqvxz";
echo customSort('ndgi', 'eqfbnjbpbisjoakfnncpaphvvzxsodaw') === "nnndiaaabbbceffhjjkoopppqssvvwxz";
echo customSort('ymd', 'duoisjfobwlztxsaymzjwvpofouyijglwgvogpt') === "yymdabffgggiijjjlloooooppssttuuvvwwwxzz";
echo customSort('wpkmv', 'crcasndkumqcckmqxcpagkjveovcmnmzvbkixeduqohkutbelm') === "pkkkkkmmmmmvvvaabbccccccddeeeghijlnnooqqqrstuuuxxz";
echo customSort('qdmbfc', 'mruwsotaydpzeezpgmmcrhbwsihrbzryqheigapvaehnyjgvbvqrdxtqkczujzqngpdmrduffcokcnfcqqmqtwbquzssalydifip') === "qqqqqqqqdddddmmmmmbbbbffffcccccaaaaeeeegggghhhhiiiijjkklnnnooppppprrrrrrsssstttuuuuvvvwwwxyyyyzzzzzz";
echo customSort('iupmz', 'ixavjrmbwacgwvxcrauvcfcizfoxxabdyossqvzubqnpdzphbpurikqzqigjdrjsycpjlpstokvnijpcchcgtdfvqkltbdqidptvbsmwxeuqxyvcyzfiksnrrzbpmxdlhzieocmabqszqanfwjqmjb') === "iiiiiiiiuuuuppppppppmmmmmzzzzzzzzaaaaaabbbbbbbbbccccccccccdddddddeefffffggghhhjjjjjjjkkkklllnnnnooooqqqqqqqqqqrrrrrrsssssssttttvvvvvvvvwwwwxxxxxxxyyyy";
echo customSort('cjhfnu', 'uokmxyzaisghuqmxxhnntlhhasjwfkjutdoumlkwfusscjspauroihkxmsvamxuqronfszjmgnqjlwdkvndslsykrojvrienrhtrvtrmacuneouorbjceadhskonhbnghctqbqkgzqwuaegumugggilhjbzqcpgbpkfxlbeyinfdrzkvesxjnmyvrwbftuymtzrzzzlm') === "cccccjjjjjjjjjhhhhhhhhhhffffffnnnnnnnnnnnuuuuuuuuuuuuuaaaaaaabbbbbbbdddddeeeeeegggggggggiiiiikkkkkkkkkklllllllmmmmmmmmmmmoooooooopppqqqqqqqrrrrrrrrrrrssssssssssstttttttvvvvvvwwwwwxxxxxxxyyyyyzzzzzzzzz";
echo customSort('novctmix', 'hufppxpeisstygylmfwgfftwagpnkzqzcizntyejrvsfxxavvezdsddcdkgogkgkqkuexycbqzdicpxdqjdyncgmiatdbshrzcdfmxyanudnynwdhunfjqqccnncolkpcylkivehdaejlndoldmwbtibzcfsvpvmbyweviedadrqjnukmemjbwpefwhuonpdysivbeybmejzcjmswrpmgieffmpsfxkmmojklnqpelfrcaojcpouzkctajfwvgddcflfksscuwopqrjyqwghnwgblavhztnaeyqgebjodyte') === "nnnnnnnnnnnnnnnooooooooovvvvvvvvvvcccccccccccccccccttttttttmmmmmmmmmmmmmiiiiiiiiixxxxxxxaaaaaaaaaabbbbbbbbbbddddddddddddddddddddeeeeeeeeeeeeeeeeeffffffffffffffffgggggggggggghhhhhhhjjjjjjjjjjjjjkkkkkkkkkkkklllllllllppppppppppppppqqqqqqqqqqqrrrrrrsssssssssssuuuuuuuuwwwwwwwwwwwwyyyyyyyyyyyyyyzzzzzzzzzz";
echo customSort('thvuybo', 'ahharlbhljltdsfdnosejlfqjiagscjzaeohishxlclidyjwujukzjosfnwafvpmifsuuefnxgxjptayqqdidesuxbdbeljravainxgqddujcrwgawdqrhzoesozymihqktdkbhwmtxyoaawgilobdpfdissmmbomfzmogjnrbwrtwaxditdnivjfajpfuoozoyaplurcmodmtfvlnxmhhmygtpxgaxsgfpynppmjbklckosakqejqcmmhbaagpwryflomemizdlfcecslcqdtwyjjksavdbzimziqiloagxebqygirghyjmiaxzyoweadutohctkmwruxpnobfoglrksfxxyk') === "ttttttttttthhhhhhhhhhhhhvvvvvuuuuuuuuuuyyyyyyyyyyyyybbbbbbbbbbbbooooooooooooooooooooaaaaaaaaaaaaaaaaaaaaaaccccccccccdddddddddddddddddddeeeeeeeeeeeffffffffffffffffggggggggggggggiiiiiiiiiiiiiiiiijjjjjjjjjjjjjjjjjjkkkkkkkkkkllllllllllllllllmmmmmmmmmmmmmmmmmmmnnnnnnnnnpppppppppppqqqqqqqqqqqrrrrrrrrrrrssssssssssssssswwwwwwwwwwwwxxxxxxxxxxxxxxxzzzzzzzzzz";
echo customSort('pgjiyhkor', 'ctocsybgtvhbobisqhxicddaiykrlyfzegnmytpuomrwybvaqcuigzehqnizepqjyamnraqprghctzxdgufqrwjfskjfyonwtbqhtjnhtqzarwawjprdckbezvvolbtcrubnpvstaaiytphclyfzxrajvailyvhnxjrwarccndmefmygpkjlurgnrijyfglcicvfgysgptqlnuqfybscgjqbufiqzpixerftznkixownsmmoqhhcfuacwmahcuxgnvvawzktcjzyofmpxbgxrmjeabkknkbkterkaqdtrekmfoleyhikdcnwnkiyacxquhyvuwdrralwypvbwmhorsvoghtjnsavtbiefeif') === "pppppppppppggggggggggggggjjjjjjjjjjjjjiiiiiiiiiiiiiiiiyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhkkkkkkkkkkkkkkooooooooooorrrrrrrrrrrrrrrrrrrraaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbcccccccccccccccccccddddddddeeeeeeeeeeeefffffffffffffffflllllllllmmmmmmmmmmmmnnnnnnnnnnnnnnnnnqqqqqqqqqqqqqqqssssssssstttttttttttttttttuuuuuuuuuuuvvvvvvvvvvvvvvwwwwwwwwwwwwwxxxxxxxxxxzzzzzzzzzzz";
echo customSort('jxrqklbgut', 'qdjufpwzuttywfbcviuyreqgmwlnejsgbapgbybohkyflajcmhikdpzszwbsmfgcbhmtxwofgjjkvcednyyphusnzvahpeaoqsshhgjslpybwzambbuwbkpnkrnpmetqfuytmhbrousmsuuinvnrlmerfdunixycgmtslmrervxmsekkrdcznyykghhdzmhwnzycqxwzolqnswwmukpxikuklwqqhkgxlknqjtpigvoivwnymxxjmikvklafgkibreppwwkwffxixgjxheyornboevxnqslwpxjeaagqvcdhytirdxyaypghxbqpodwrrgyovsgcjrealijagpeiklkbzlpskkratjnoowdpunvfdmgjsitasevwjxrnyjoexhhgrgizoyszuzosaaxugpaopkpqrpkxbchygmovixndcggrvnjxazuphbztcumvntlqrxihojlkiwydtabdnhxjedbnircuwzbbikguyjucwuqwvohb') === "jjjjjjjjjjjjjjjjjjjjxxxxxxxxxxxxxxxxxxxxxxxrrrrrrrrrrrrrrrrrrrrrqqqqqqqqqqqqqqqkkkkkkkkkkkkkkkkkkkkkkkkklllllllllllllllbbbbbbbbbbbbbbbbbbbbbbggggggggggggggggggggggggguuuuuuuuuuuuuuuuuuuuutttttttttttttaaaaaaaaaaaaaaaaaaccccccccccccccdddddddddddddddeeeeeeeeeeeeeeeeefffffffffffhhhhhhhhhhhhhhhhhhhhhhiiiiiiiiiiiiiiiiiiiimmmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnnnnnnnooooooooooooooooooopppppppppppppppppppppppsssssssssssssssssssvvvvvvvvvvvvvvvvvwwwwwwwwwwwwwwwwwwwwwwwwyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzz";
echo customSort('vupdsfgrxkob', 'qqxaqgcnyxpskszwdgcfziyhamuursywnpyagjeffyiiduegqxyjvjgbifixwlrcdhhlnviurfuwqzdvoxqlrxhzncaovazhsiovnutkroznckeuawhlamsvvpmrvpdnovzmtrnyohgybsemqzcxlcwryqfeseqxkqqdqqhholzssrqsrnswqgqteajockivqqkjmmafdkswbduaelhqqbmslrygrudswaziadrdwfmicnmdtmrwgxmuxipmnjbhdobbknepdewivqwnfdxnkzdzdtgcbafvjgaolbptzfjexjkbgrsajmcgyeivgneyyltfgaeqgzzmtfkkokfhwdhvmhhemcnfngjgjupjgcwtmtzuuvsexrhbzqxlfwfyeswevyetwpwmfvmhwrvgjxbgkarinrqavoeeujkthnoimatblovywbkjkwqijkkxizlrpqqsmqwaitwrgmrxcaipshowtkmecmigwufqsqxbjdyntvcpgfqcbmnjlvvftecppcdfecsbkulqozslpybgzfuyjlfldokvrkeqikxjpszdtoebwwekbfemrxlbcqsvpopzqabixdrhfeyiqtkh') === "vvvvvvvvvvvvvvvvvvvvvvvvvuuuuuuuuuuuuuuuuuppppppppppppppppppdddddddddddddddddddddddssssssssssssssssssssssssffffffffffffffffffffffffffgggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeehhhhhhhhhhhhhhhhhhhhhiiiiiiiiiiiiiiiiiiiiiiijjjjjjjjjjjjjjjjjjjjjlllllllllllllllllllmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnnnnnqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqtttttttttttttttttttwwwwwwwwwwwwwwwwwwwwwwwwwwwwyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzz";
echo customSort('opdzsivgarylwut', 'alvvrdrpodmnqtlvmzbacxvxdmewsianihbdhnbiwhdzxnpkzvanawjkcqszvlslhxuanzdswpfvutldiwvskctbxzapqjvrfnymebzvqmvprtrmjgngzwpcdxmjkvbfuzyjrlvyizvbqcffjizgcyqkggzocifneiwkcwvdxzhdrjcrnrjdugnhzfpnmoxbczbqrupyyrumlbetwzaualwykciqxllxuermbdphxjwprprvmehowzxtyagrlezarcxwywgezsxxnwxdrmwoaakksfxipklmghcxltsncwqwnivztepxgjnwhizufgfakswgcqykysqiucwveponhvunirxwtmafbfrugnntjhadqggnerfkxfpipxpxeruauaaexvzxsonopkxeaxmachfxjjdtoxutrqvgydvevtjwltkxeiggxkhbecsqigqfqjqazfncbgxalbzsxpksvlvtqqwcvnqpvnqvfqqnufdojpjomsbpalfnwbrtdvhetvxdjpnxoftlplthcdfgzlzqsdooiacopqsjumjmnbqeuspusrpbpxnxgfxnqdlstxmfczqburziytvkcxdskkzkrisxycrtlpaathgiligmgywbnmynkumhmovagynbrlvljubifkwivrqhsykamixhhvdfngauifhwpkziutxqoqngsjbjcklrultvjshkmpmlchflzpgmvgrzkqsrxmicikvbgbzmmypzzbcndxjpqejhhktvngzqtlwiuhqjnanqqpgnlfvogchjzsqwtsdwljqvjqazhpuhxyhwzpofembzxdofktxeozijzfocewsojmrpgcamplqfsdxbognpdtkxpogqanlvzmicgfrnkgwwwvsxfpaywesmysmqqsny') === "oooooooooooooooooooooooooppppppppppppppppppppppppppppppppppppppppppdddddddddddddddddddddddddddddzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzssssssssssssssssssssssssssssssssssiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvgggggggggggggggggggggggggggggggggggggggaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrryyyyyyyyyyyyyyyyyyyyyyyllllllllllllllllllllllllllllllllllwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwuuuuuuuuuuuuuuuuuuuuuuuuuuuttttttttttttttttttttttttttttttbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeefffffffffffffffffffffffffffffffffffhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

// Author: Evgeny SH